# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/simple_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 697)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 140, 821, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(40)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_user_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_user_name.setObjectName("le_user_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_user_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_Password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_Password.setObjectName("le_Password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_Password)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(310, 270, 83, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "User Name"))
        self.label_2.setText(_translate("Form", "Password"))
        self.le_Password.setPlaceholderText(_translate("Form", "enter a password"))
        self.pushButton.setText(_translate("Form", "Send"))
